[env:n16r8]
extends = esp32s3_base
board = esp32-s3-devkitc-1

board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi

monitor_filters = esp32_exception_decoder
upload_speed    = 921600
monitor_speed   = 115200

build_unflags =
    ${esp32s3_base.build_unflags}
    -flto

build_flags =
    ${esp32s3_base.build_flags}
    -D PRIVATE_HW
    -I variants/esp32s3/n16r8
    ; Display: ST7789 320x172 landscape
    -D ST7789_SPI_HOST=SPI2_HOST
    ; Phase 1: nothing else wired yet
    -D HAS_GPS=0
    -D HAS_SCREEN=1

lib_deps =
    ${esp32s3_base.lib_deps}
    lovyan03/LovyanGFX@1.2.21
    ; ST7789 SPI driver
    https://github.com/meshtastic/st7789/archive/5180423ae2dbf5885168a8bfb308c7fb7eff6930.zip

board_level = extra
