; The Elecrow sx1262 and nrf52 module
[env:elecrow_lr1262]
extends = nrf52840_base
board = elecrow-lr1262
board_level = extra
extra_scripts =
  ${env.extra_scripts}

# Remove adafruit USB serial from the build (it is incompatible with using the ch340 serial chip on this board)
build_unflags = ${nrf52840_base:build_unflags} -DUSBCON -DUSE_TINYUSB
build_flags = ${nrf52840_base.build_flags}
  -Ivariants/nrf52840/diy/elecrow_lr1262
  -Isrc/platform/nrf52/softdevice
  -Isrc/platform/nrf52/softdevice/nrf52
  -DPRIVATE_HW
  -DCFG_TUD_CDC=0
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/elecrow_lr1262>

;debug_tool = jlink
debug_tool = stlink
; No need to reflash if the binary hasn't changed

; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
;upload_protocol = nrfutil
;upload_protocol = stlink
