[env:n16r8-minimal]
extends = esp32s3_base
board = esp32-s3-devkitc-1

board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi

monitor_speed = 115200

build_flags =
    ${esp32s3_base.build_flags}
    -D PRIVATE_HW
    -I variants/esp32s3/diy/n16r8_minimal
    -D BOARD_HAS_PSRAM

board_level = extra
